In [12]:
# Dowland the liabries we need them in the project
import numpy as np
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [19]:
#read csv file
df=pd.read_csv('./')

FileNotFoundError: [Errno 2] No such file or directory: '2021.csv'

In [14]:
#see the columns and types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 324818 entries, 0 to 324817
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ﻿N                    324818 non-null  int64
 1   Year                  324818 non-null  int64
 2   Month                 324818 non-null  str
 3   Commodity No          324818 non-null  int64
 4   Commodity             324818 non-null  str
 5   السلعة                324818 non-null  str
 6   UN code               324759 non-null  str
 7   Country Name          324818 non-null  str
 8   الدولة                324818 non-null  str
 9   Import Value (BD)     324818 non-null  float64
 10  Import Value (USA $)  324818 non-null  float64
 11  Import Weight (KG)    324818 non-null  float64
 12  Import Quantity       324818 non-null  float64
 13  UM                    324818 non-null  str
dtypes: float64(4), int64(3), str(7)
memory usage: 86.8 MB

In [11]:
#see the data and read them
df.head()

,﻿N,Year,Month,Commodity No,Commodity,السلعة,UN code,Country Name,الدولة,Import Value (BD),Import Value (USA $),Import Weight (KG),Import Quantity,UM
0,1,2025,01 January,1012910,HORSES FOR SPORT,خيول للرياضة,GB,UNITED KINGDOM,المملكة المتحدة,408.846,1087.356383,900.0,2.0,NO
1,2,2025,01 January,1012990,Other HORSES,غيرها من خيول آخر,HU,HUNGARY,هنغاريا,374.229,995.289894,200.0,1.0,NO
2,3,2025,01 January,1022900,OTHER BOVINE,غيرها من ابقار,SO,SOMALIA,الصومال,155793.354,414344.026600,105000.0,637.0,NO
3,4,2025,01 January,1041090,OTHER SHEEP,حيوانات من فصيلة الضان اخر,IR,IRAN,جمهورية إيران الإسلامية,275353.514,732323.175500,96800.0,3060.0,NO
4,5,2025,01 January,1041090,OTHER SHEEP,حيوانات من فصيلة الضان اخر,SO,SOMALIA,الصومال,263593.513,701046.577100,95000.0,6438.0,NO

In [16]:
#drop the columns we do not need them (the duplicated)
df1 = df.drop(columns=['السلعة', 'الدولة'])
df1

,﻿N,Year,Month,Commodity No,Commodity,UN code,Country Name,Import Value (BD),Import Value (USA $),Import Weight (KG),Import Quantity,UM
0,1,2025,01 January,1012910,HORSES FOR SPORT,GB,UNITED KINGDOM,408.846,1.087356e+03,900.00,2.00,NO
1,2,2025,01 January,1012990,Other HORSES,HU,HUNGARY,374.229,9.952899e+02,200.00,1.00,NO
2,3,2025,01 January,1022900,OTHER BOVINE,SO,SOMALIA,155793.354,4.143440e+05,105000.00,637.00,NO
3,4,2025,01 January,1041090,OTHER SHEEP,IR,IRAN,275353.514,7.323232e+05,96800.00,3060.00,NO
4,5,2025,01 January,1041090,OTHER SHEEP,SO,SOMALIA,263593.513,7.010466e+05,95000.00,6438.00,NO
...,...,...,...,...,...,...,...,...,...,...,...,...
324813,324814,2025,12 December,98010000,THE PERSONAL EFFECTS AND USED HOUSEHOLD APPLIA...,TR,TURKEY,101.000,2.686170e+02,905.00,905.00,KG
324814,324815,2025,12 December,98010000,THE PERSONAL EFFECTS AND USED HOUSEHOLD APPLIA...,TT,TRINIDAD&TOBAGO,3030.000,8.058511e+03,3756.00,3756.00,KG
324815,324816,2025,12 December,98010000,THE PERSONAL EFFECTS AND USED HOUSEHOLD APPLIA...,US,UNITED STATES OF AMERICA,2600.514,6.916261e+03,955.00,955.00,KG
324816,324817,2025,12 December,98010000,THE PERSONAL EFFECTS AND USED HOUSEHOLD APPLIA...,XB,Returned Bahrain Goods,189.921,5.051090e+02,2110.20,2110.20,KG
324817,324818,2025,12 December,98980000,Confidential Goods,QX,COUNTRIES AND TERRITORIES NOT SPECIFIED FOR CO...,455311.606,1.210935e+06,23778.99,23778.99,KG

In [17]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 324818 entries, 0 to 324817
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ﻿N                    324818 non-null  int64
 1   Year                  324818 non-null  int64
 2   Month                 324818 non-null  str
 3   Commodity No          324818 non-null  int64
 4   Commodity             324818 non-null  str
 5   UN code               324759 non-null  str
 6   Country Name          324818 non-null  str
 7   Import Value (BD)     324818 non-null  float64
 8   Import Value (USA $)  324818 non-null  float64
 9   Import Weight (KG)    324818 non-null  float64
 10  Import Quantity       324818 non-null  float64
 11  UM                    324818 non-null  str
dtypes: float64(4), int64(3), str(5)
memory usage: 50.0 MB

In [ ]:
#change the quantity to be integer